name: flutter_video_thumbnail_plus
description: "A Flutter package for generating thumbnails from video files and byte arrays, supporting various image formats and customization options."
version: 1.0.2
homepage: https://github.com/rahulsaryam285/flutter_video_thumbnail_plus

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_video_thumbnail_plus
        pluginClass: FlutterVideoThumbnailPlusPlugin
      ios:
        pluginClass: FlutterVideoThumbnailPlusPlugin
      web:
        pluginClass: FlutterVideoThumbnailPlusWeb
        fileName: flutter_video_thumbnail_plus_web.dart
  uses-material-design: true
